"""add_trading_tables

Revision ID: 43a3029f6547
Revises: 9bedb82c9f31
Create Date: 2026-03-24 16:00:42.100515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43a3029f6547'
down_revision: Union[str, None] = '9bedb82c9f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('paper', 'live', name='tradingmode'), nullable=False),
    sa.Column('app_key', sa.Text(), nullable=False),
    sa.Column('app_secret', sa.Text(), nullable=False),
    sa.Column('account_number', sa.Text(), nullable=False),
    sa.Column('account_product_code', sa.String(length=2), nullable=False),
    sa.Column('initial_capital', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mode', name='uq_trading_account_user_mode')
    )
    op.create_index(op.f('ix_trading_accounts_user_id'), 'trading_accounts', ['user_id'], unique=False)
    op.create_table('trading_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('ticker_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Text(), nullable=False),
    sa.Column('avg_buy_price', sa.Text(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('unrealized_pnl', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'ticker', name='uq_trading_position_account_ticker')
    )
    op.create_index(op.f('ix_trading_positions_user_id'), 'trading_positions', ['user_id'], unique=False)
    op.create_table('trading_strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy_type', sa.Enum('ma_crossover', 'mean_reversion', 'custom', name='strategytype'), nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_tickers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('market_hours_only', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_strategies_user_id'), 'trading_strategies', ['user_id'], unique=False)
    op.create_table('trading_schedule_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('success', 'skipped', 'error', name='schedulelogstatus'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tickers_evaluated', sa.Integer(), nullable=False),
    sa.Column('orders_placed', sa.Integer(), nullable=False),
    sa.Column('orders_filled', sa.Integer(), nullable=False),
    sa.Column('realized_pnl', sa.Text(), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['trading_strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trading_schedule_logs_user_executed', 'trading_schedule_logs', ['user_id', 'executed_at'], unique=False)
    op.create_table('trading_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('schedule_log_id', sa.UUID(), nullable=True),
    sa.Column('side', sa.Enum('buy', 'sell', name='orderside'), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('ticker_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Text(), nullable=False),
    sa.Column('price', sa.Text(), nullable=False),
    sa.Column('filled_quantity', sa.Text(), nullable=True),
    sa.Column('filled_price', sa.Text(), nullable=True),
    sa.Column('order_type', sa.Enum('market', 'limit', name='ordertype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'submitted', 'filled', 'partial', 'cancelled', 'rejected', name='orderstatus'), nullable=False),
    sa.Column('kis_order_id', sa.String(length=50), nullable=True),
    sa.Column('kis_order_date', sa.String(length=8), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_log_id'], ['trading_schedule_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['trading_strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trading_orders_schedule_log', 'trading_orders', ['schedule_log_id'], unique=False)
    op.create_index('ix_trading_orders_user_created', 'trading_orders', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trading_orders_user_created', table_name='trading_orders')
    op.drop_index('ix_trading_orders_schedule_log', table_name='trading_orders')
    op.drop_table('trading_orders')
    op.drop_index('ix_trading_schedule_logs_user_executed', table_name='trading_schedule_logs')
    op.drop_table('trading_schedule_logs')
    op.drop_index(op.f('ix_trading_strategies_user_id'), table_name='trading_strategies')
    op.drop_table('trading_strategies')
    op.drop_index(op.f('ix_trading_positions_user_id'), table_name='trading_positions')
    op.drop_table('trading_positions')
    op.drop_index(op.f('ix_trading_accounts_user_id'), table_name='trading_accounts')
    op.drop_table('trading_accounts')
    # ### end Alembic commands ###
