"""add telegram_chat_id to users and alert state fields to watchlists

Revision ID: aabb3fbb826b
Revises: e1a5703588a9
Create Date: 2026-03-27 16:17:55.706933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabb3fbb826b'
down_revision: Union[str, None] = 'e1a5703588a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=100), nullable=True))
    op.add_column('watchlists', sa.Column('alerted_target_buy', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('watchlists', sa.Column('alerted_target_sell', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('watchlists', sa.Column('alerted_threshold', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlists', 'alerted_threshold')
    op.drop_column('watchlists', 'alerted_target_sell')
    op.drop_column('watchlists', 'alerted_target_buy')
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###
